on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
name: Create Release

jobs:
  build_and_test:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test --if-present
      - name: Archive artifacts
        id: archive_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-release
          retention-days: 1
          path: |
            release
            config
            ./customFramework.js
            ./README.md
            ./fxmanifest.lua
      - name: Download Artifact
        uses: actions/download-artifact@v4
        id: download_artifacts
        with:
          name: artifact-release
          path: dist/release
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "${{ steps.download_artifacts.outputs.download-path }}/artifact-release.zip"
          asset_name: dumpsterdive.release.zip
          asset_content_type: application/zip
